
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tusar
 */
public class ChangeEmpFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChangeEmpFrame
     */
    public ChangeEmpFrame() {
        initComponents();
        statusSelector.addItem("Full Time");
        statusSelector.addItem("Part Time");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chgEmp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        statusSelector = new javax.swing.JComboBox<>();
        fNameLabel = new javax.swing.JLabel();
        lNameLabel = new javax.swing.JLabel();
        fNameInput = new javax.swing.JTextField();
        lNameInput = new javax.swing.JTextField();
        locLabel = new javax.swing.JLabel();
        locInput = new javax.swing.JTextField();
        deductLabel = new javax.swing.JLabel();
        deductInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        incomeLabel = new javax.swing.JLabel();
        pteWageLabel = new javax.swing.JLabel();
        pteHPWLabel = new javax.swing.JLabel();
        pteWPYLabel = new javax.swing.JLabel();
        pteWageInput = new javax.swing.JTextField();
        pteWPYInput = new javax.swing.JTextField();
        pteHPWInput = new javax.swing.JTextField();
        chgEmpButton = new javax.swing.JButton();
        empNumInpLabel = new javax.swing.JLabel();
        empNumInput = new javax.swing.JTextField();
        genLabel = new javax.swing.JLabel();
        genInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chgEmp.setText("Employee Number");
        chgEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chgEmpFocusGained(evt);
            }
        });

        jLabel1.setText("Employee to Change:");

        statusSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        statusSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusSelectorActionPerformed(evt);
            }
        });

        fNameLabel.setText("First Name:");

        lNameLabel.setText("Last Name:");

        fNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameInputActionPerformed(evt);
            }
        });

        lNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameInputActionPerformed(evt);
            }
        });

        locLabel.setText("Location(City):");

        locInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locInputActionPerformed(evt);
            }
        });

        deductLabel.setText("Deduction Rate:");

        deductInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductInputActionPerformed(evt);
            }
        });

        jLabel6.setText("Select Employee Status:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Personal Information");

        incomeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        incomeLabel.setText("Income Information");

        pteWageLabel.setText("Hourly Wage:");

        pteHPWLabel.setText("Hours Per Week:");

        pteWPYLabel.setText("Weeks Per Year:");

        pteWPYInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pteWPYInputActionPerformed(evt);
            }
        });

        pteHPWInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pteHPWInputActionPerformed(evt);
            }
        });

        chgEmpButton.setText("Change Data");
        chgEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chgEmpButtonActionPerformed(evt);
            }
        });

        empNumInpLabel.setText("Employee Number:");

        empNumInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumInputActionPerformed(evt);
            }
        });

        genLabel.setText("Gender:");

        genInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chgEmpButton)
                    .addComponent(statusSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empNumInpLabel)
                            .addComponent(locLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(locInput, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(empNumInput)
                            .addComponent(genInput)
                            .addComponent(lNameInput)
                            .addComponent(fNameInput)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(incomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pteWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pteHPWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pteWPYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pteHPWInput)
                                .addComponent(pteWPYInput)
                                .addComponent(deductInput)
                                .addComponent(pteWageInput))))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chgEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chgEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(statusSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLabel)
                    .addComponent(fNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameLabel)
                    .addComponent(lNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locLabel)
                    .addComponent(locInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNumInpLabel)
                    .addComponent(empNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genLabel)
                    .addComponent(genInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(incomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deductInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pteWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pteWageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pteHPWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pteHPWInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pteWPYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pteWPYInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chgEmpButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusSelectorActionPerformed
        // TODO add your handling code here:
        if (statusSelector.getSelectedIndex() == 0) {
            // Full Time selected
            pteWageLabel.setText("Yearly Salary");
            pteHPWLabel.setVisible(false);
            pteWPYLabel.setVisible(false);
            pteHPWInput.setVisible(false);
            pteWPYInput.setVisible(false);
        }
        else {
            // Part Time selected
            System.out.println("pte");
            pteWageLabel.setText("Hourly Wage:");
            pteHPWLabel.setVisible(true);
            pteWPYLabel.setVisible(true);
            pteHPWInput.setVisible(true);
            pteWPYInput.setVisible(true);
        }

    }//GEN-LAST:event_statusSelectorActionPerformed

    private void fNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameInputActionPerformed

    private void lNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameInputActionPerformed

    private void locInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locInputActionPerformed

    private void pteWPYInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pteWPYInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pteWPYInputActionPerformed

    private void pteHPWInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pteHPWInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pteHPWInputActionPerformed

    private void chgEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chgEmpButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) MainJFrame.getEmpTable().getModel();
        int numRows = model.getRowCount();
        MyHashTable tempTable = MainJFrame.table;
        
        int empNum = Integer.valueOf(empNumInput.getText());
        String fName = fNameInput.getText();
        String lName = lNameInput.getText();
        String gender = genInput.getText();
        String location = locInput.getText();
        double deductR = Double.valueOf(deductInput.getText());
        

        if (statusSelector.getSelectedIndex() == 0) {
            int empToChange = Integer.valueOf(chgEmp.getText());
            
            EmployeeInfo employee = tempTable.getFromTable(empToChange);
            
            
            double yearlyS = Double.valueOf(pteWageInput.getText());
            String s = "Full Time";
            
            FTE chgdEmp = new FTE(empNum, fName, lName, gender, location, deductR, s, yearlyS);

            int bucketsIndex = tempTable.calcBucket(empToChange);
            int empChangeIndex = tempTable.buckets[bucketsIndex].indexOf(employee);
            
            tempTable.buckets[bucketsIndex].set(empChangeIndex, chgdEmp);
            
            for (int i = 0; i < numRows; i ++) {
                int checkNum = (int) model.getValueAt(i,0);
                
                if (checkNum == empToChange) {
                    model.setValueAt(chgdEmp.empNum, i, 0);
                    model.setValueAt(chgdEmp.firstName, i, 1);
                    model.setValueAt(chgdEmp.lastName, i, 2);
                    model.setValueAt(chgdEmp.workLoc, i, 3);
                    model.setValueAt(chgdEmp.status, i, 4);
                }
            } 
        } else {
            //PTE(int eN, String fN, String lN, String g, String wL, double dR, double hW, double hPW, double wPY, String status)
            int empToChange = Integer.valueOf(chgEmp.getText());
            
            EmployeeInfo employee = tempTable.getFromTable(empToChange);
            
            double hourlyWage = Double.valueOf(pteWageInput.getText());
            double hoursPWeek = Double.valueOf(pteHPWInput.getText());
            double weeksPYear = Double.valueOf(pteWPYInput.getText());
            String s = "Part Time";
            
            PTE chgdEmp = new PTE(empNum, fName, lName, gender, location, deductR, s, hourlyWage, hoursPWeek, weeksPYear);
            
            int bucketsIndex = tempTable.calcBucket(empToChange);
            int empChangeIndex = tempTable.buckets[bucketsIndex].indexOf(employee);
            
            tempTable.buckets[bucketsIndex].set(empChangeIndex, chgdEmp);
            
            for (int i = 0; i < numRows; i ++) {
                int checkNum = (int) model.getValueAt(i,0);
                
                if (checkNum == empToChange) {
                    model.setValueAt(chgdEmp.empNum, i, 0);
                    model.setValueAt(chgdEmp.firstName, i, 1);
                    model.setValueAt(chgdEmp.lastName, i, 2);
                    model.setValueAt(chgdEmp.workLoc, i, 3);
                    model.setValueAt(chgdEmp.status, i, 4);
                }
            } 
            
        }

        this.dispose();
    }//GEN-LAST:event_chgEmpButtonActionPerformed

    private void empNumInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumInputActionPerformed

    private void genInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genInputActionPerformed

    private void chgEmpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chgEmpFocusGained
        // TODO add your handling code here:
        chgEmp.setText("");
    }//GEN-LAST:event_chgEmpFocusGained

    private void deductInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deductInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeEmpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chgEmp;
    private javax.swing.JButton chgEmpButton;
    private javax.swing.JTextField deductInput;
    private javax.swing.JLabel deductLabel;
    private javax.swing.JLabel empNumInpLabel;
    private javax.swing.JTextField empNumInput;
    private javax.swing.JTextField fNameInput;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField genInput;
    private javax.swing.JLabel genLabel;
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lNameInput;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JTextField locInput;
    private javax.swing.JLabel locLabel;
    private javax.swing.JTextField pteHPWInput;
    private javax.swing.JLabel pteHPWLabel;
    private javax.swing.JTextField pteWPYInput;
    private javax.swing.JLabel pteWPYLabel;
    private javax.swing.JTextField pteWageInput;
    private javax.swing.JLabel pteWageLabel;
    private javax.swing.JComboBox<String> statusSelector;
    // End of variables declaration//GEN-END:variables
}
